IF
	HPPercentLT(Myself,50)
	HasItem("potn52",Myself)
THEN
	RESPONSE #100
	DisplayStringHead(Myself,46150)//quaffs a potion
	UseItem("potn52",Myself)
	Continue()
END

IF
	OR(2)
	  AttackedBy([GOODCUTOFF],DEFAULT)
	  Heard([ANYONE],99)
	!Allegiance(Myself,ENEMY)
	THEN
	RESPONSE #100
	Shout(99)
	EquipMostDamagingMelee()
	Enemy()
END

IF
	See(NearestEnemyOfType([GOODCUTOFF]))
THEN
	RESPONSE #100
	EquipMostDamagingMelee()
	AttackReevaluate(NearestEnemyOfType([GOODCUTOFF]),30)
END
